name: cynk

environment:
  sdk: 3.6.1
  flutter: 3.27.2

dependencies:
  bloc: ^8.0.1
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.0
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  rxdart: ^0.28.0
  timeago: ^3.2.2
  universal_html: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  leancode_lint: ^14.2.0

flutter:
  uses-material-design: true
  generate: true
