name: Cynk

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  bloc_concurrency: ^0.2.5
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_mobx: ^2.2.1+1
  go_router: ^14.6.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  mobx: ^2.4.0
  provider: ^6.1.2
  timeago: ^3.2.2

dev_dependencies:
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  leancode_lint: ^14.2.0
  mobx_codegen: ^2.6.2

flutter:
  uses-material-design: true
