name: cynk

environment:
  sdk: 3.6.1
  flutter: 3.27.2

dependencies:
  bloc_concurrency: ^0.2.5
  cloud_firestore: ^5.6.0
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.6.1
  google_sign_in: ^6.2.2
  intl: ^0.17.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  timeago: ^3.2.2

dev_dependencies:
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  leancode_lint: ^14.2.0

flutter:
  uses-material-design: true
