// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDn4Q9X4pHorAtgBq8BazUTrwQDf_P5D8',
    appId: '1:410051796583:web:b9af079789fc03f802fec2',
    messagingSenderId: '410051796583',
    projectId: 'cynk-app',
    authDomain: 'cynk-app.firebaseapp.com',
    storageBucket: 'cynk-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGoMe_nGlVRla2IoXIcLNu2LSmmhmmGbs',
    appId: '1:410051796583:android:44a894c813de073c02fec2',
    messagingSenderId: '410051796583',
    projectId: 'cynk-app',
    storageBucket: 'cynk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRktYEpc1rTRgEEbF26c3vxVrqkIOHQA',
    appId: '1:410051796583:ios:364e1089ec4ac17d02fec2',
    messagingSenderId: '410051796583',
    projectId: 'cynk-app',
    storageBucket: 'cynk-app.firebasestorage.app',
    iosClientId: '410051796583-kg9f0annbiurkmp3ms86aeldt7sp1ktr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cynk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzRktYEpc1rTRgEEbF26c3vxVrqkIOHQA',
    appId: '1:410051796583:ios:364e1089ec4ac17d02fec2',
    messagingSenderId: '410051796583',
    projectId: 'cynk-app',
    storageBucket: 'cynk-app.firebasestorage.app',
    iosClientId: '410051796583-kg9f0annbiurkmp3ms86aeldt7sp1ktr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cynk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDn4Q9X4pHorAtgBq8BazUTrwQDf_P5D8',
    appId: '1:410051796583:web:e675b86579364b9d02fec2',
    messagingSenderId: '410051796583',
    projectId: 'cynk-app',
    authDomain: 'cynk-app.firebaseapp.com',
    storageBucket: 'cynk-app.firebasestorage.app',
  );

}